-- generated by newgenasym Thu Mar 05 15:30:22 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74avc4t245_bris\ is
    port (    
	\1a\:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\1b\:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\1dir\:    IN     STD_LOGIC;    
	\1oe*\:    IN     STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\2b\:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\2dir\:    IN     STD_LOGIC;    
	\2oe*\:    IN     STD_LOGIC);
end \74avc4t245_bris\;
