// generated by newgenasym  Wed Mar 04 16:25:40 2020


module i2c_level_translate (scla, sclb, sdaa, sdab);
    input scla;
    output sclb;
    inout sdaa;
    inout sdab;


    initial
        begin
        end

endmodule
