-- generated by newgenasym Wed Mar 04 16:25:40 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity i2c_level_translate is
    port (    
	SCLA:      IN     STD_LOGIC;    
	SCLB:      OUT    STD_LOGIC;    
	SDAA:      INOUT  STD_LOGIC;    
	SDAB:      INOUT  STD_LOGIC);
end i2c_level_translate;
