// generated by newgenasym  Fri Jun  3 09:10:42 2016


module lp38692sd (dap, en, gnd, in1, in2, out, sns);
    input dap;
    input en;
    input gnd;
    input in1;
    input in2;
    output out;
    input sns;


    initial
        begin
        end

endmodule
