// generated by newgenasym  Mon Feb 03 15:54:24 2020


module fmc_lpc_generic (clk0_m2c_n, clk0_m2c_p, clk1_m2c_n, clk1_m2c_p,
        dp0_c2m_n, dp0_c2m_p, dp0_m2c_n, dp0_m2c_p, ga0, ga1,
        gbtclk0_m2c_n, gbtclk0_m2c_p, la_n, la_p, pg_c2m,
        prsnt_m2c_l, scl, sda, tck, tdi, tdo, tms, trst_l, vref_a_m2c);
    input clk0_m2c_n;
    input clk0_m2c_p;
    input clk1_m2c_n;
    input clk1_m2c_p;
    output dp0_c2m_n;
    output dp0_c2m_p;
    input dp0_m2c_n;
    input dp0_m2c_p;
    output ga0;
    output ga1;
    input gbtclk0_m2c_n;
    input gbtclk0_m2c_p;
    inout [0:33] la_n;
    inout [0:33] la_p;
    output pg_c2m;
    input prsnt_m2c_l;
    output scl;
    inout sda;
    output tck;
    output tdi;
    input tdo;
    output tms;
    output trst_l;
    input vref_a_m2c;


    initial
        begin
        end

endmodule
