// generated by newgenasym  Fri Jan 31 13:20:26 2020


module sfp_module (clk_n, clk_p, los, rd_n, rd_p, sfp_scl, sfp_sda, td_n, td_p,
        tx_disable, tx_fault);
    input clk_n;
    input clk_p;
    output los;
    output rd_n;
    output rd_p;
    input sfp_scl;
    inout sfp_sda;
    input td_n;
    input td_p;
    input tx_disable;
    output tx_fault;


    initial
        begin
        end

endmodule
