-- generated by newgenasym Fri Jan 31 13:20:26 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sfp_module is
    port (    
	CLK_N:     IN     STD_LOGIC;    
	CLK_P:     IN     STD_LOGIC;    
	LOS:       OUT    STD_LOGIC;    
	RD_N:      OUT    STD_LOGIC;    
	RD_P:      OUT    STD_LOGIC;    
	SFP_SCL:   IN     STD_LOGIC;    
	SFP_SDA:   INOUT  STD_LOGIC;    
	TD_N:      IN     STD_LOGIC;    
	TD_P:      IN     STD_LOGIC;    
	TX_DISABLE: IN     STD_LOGIC;    
	TX_FAULT:  OUT    STD_LOGIC);
end sfp_module;
