-- generated by newgenasym Wed Mar 04 16:18:27 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity i2c_level_shift is
    port (    
	SCLA:      IN     STD_LOGIC;    
	SDAA:      IN     STD_LOGIC;    
	SDAB:      OUT    STD_LOGIC);
end i2c_level_shift;
