-- generated by newgenasym Mon Dec 10 10:58:18 2001

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity p12v is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end p12v;
