// generated by newgenasym  Wed May  8 17:18:12 2024


module \74axc8t245  (a, b, dir, \oe* );
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;
    input dir;
    input \oe* ;


    initial
        begin
        end

endmodule
