-- generated by newgenasym Wed May  8 17:18:12 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74axc8t245\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	DIR:       IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC);
end \74axc8t245\;
