// generated by newgenasym  Mon Mar 02 12:55:01 2020


module diff_buff_1to2 (in_n, in_p, q0_n, q0_p, q1_n, q1_p);
    input in_n;
    input in_p;
    output q0_n;
    output q0_p;
    output q1_n;
    output q1_p;


    initial
        begin
        end

endmodule
