-- generated by newgenasym Mon Mar 02 12:55:01 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diff_buff_1to2 is
    port (    
	IN_N:      IN     STD_LOGIC;    
	IN_P:      IN     STD_LOGIC;    
	Q0_N:      OUT    STD_LOGIC;    
	Q0_P:      OUT    STD_LOGIC;    
	Q1_N:      OUT    STD_LOGIC;    
	Q1_P:      OUT    STD_LOGIC);
end diff_buff_1to2;
