// generated by newgenasym  Mon Mar 09 11:17:43 2020


module mp20075_reg (ddq, en, gnd, pad, ref, vdrv, vtt, vttref, vttsen);
    input ddq;
    input en;
    input gnd;
    input pad;
    input ref;
    input vdrv;
    output vtt;
    output vttref;
    input vttsen;


    initial
        begin
        end

endmodule
