-- generated by newgenasym Mon Mar 09 11:17:43 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mp20075_reg is
    port (    
	DDQ:       IN     STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	PAD:       IN     STD_LOGIC;    
	REF:       IN     STD_LOGIC;    
	VDRV:      IN     STD_LOGIC;    
	VTT:       OUT    STD_LOGIC;    
	VTTREF:    OUT    STD_LOGIC;    
	VTTSEN:    IN     STD_LOGIC);
end mp20075_reg;
