-- generated by newgenasym Mon Feb 03 15:54:24 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fmc_lpc_generic is
    port (    
	CLK0_M2C_N: IN     STD_LOGIC;    
	CLK0_M2C_P: IN     STD_LOGIC;    
	CLK1_M2C_N: IN     STD_LOGIC;    
	CLK1_M2C_P: IN     STD_LOGIC;    
	DP0_C2M_N: OUT    STD_LOGIC;    
	DP0_C2M_P: OUT    STD_LOGIC;    
	DP0_M2C_N: IN     STD_LOGIC;    
	DP0_M2C_P: IN     STD_LOGIC;    
	GA0:       OUT    STD_LOGIC;    
	GA1:       OUT    STD_LOGIC;    
	GBTCLK0_M2C_N: IN     STD_LOGIC;    
	GBTCLK0_M2C_P: IN     STD_LOGIC;    
	LA_N:      INOUT  STD_LOGIC_VECTOR (0 TO 33);    
	LA_P:      INOUT  STD_LOGIC_VECTOR (0 TO 33);    
	PG_C2M:    OUT    STD_LOGIC;    
	PRSNT_M2C_L: IN     STD_LOGIC;    
	SCL:       OUT    STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TCK:       OUT    STD_LOGIC;    
	TDI:       OUT    STD_LOGIC;    
	TDO:       IN     STD_LOGIC;    
	TMS:       OUT    STD_LOGIC;    
	TRST_L:    OUT    STD_LOGIC;    
	VREF_A_M2C: IN     STD_LOGIC);
end fmc_lpc_generic;
