// generated by newgenasym  Wed Mar 04 16:04:59 2020


module tca9803 (en, scla, sclb, sdaa, sdab, vcca, vccb);
    input en;
    inout scla;
    inout sclb;
    inout sdaa;
    inout sdab;
    input vcca;
    input vccb;


    initial
        begin
        end

endmodule
