-- generated by newgenasym Wed Mar 04 16:04:59 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tca9803 is
    port (    
	EN:        IN     STD_LOGIC;    
	SCLA:      INOUT  STD_LOGIC;    
	SCLB:      INOUT  STD_LOGIC;    
	SDAA:      INOUT  STD_LOGIC;    
	SDAB:      INOUT  STD_LOGIC;    
	VCCA:      IN     STD_LOGIC;    
	VCCB:      IN     STD_LOGIC);
end tca9803;
