// generated by newgenasym  Thu Nov 04 18:05:00 2010


module inductance (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
