-- generated by newgenasym Mon Dec 10 11:26:49 2001

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity p3v3a is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end p3v3a;
