// generated by newgenasym  Wed May 20 13:40:49 2020


module fmc_hpc_generic (clk_bidir_n, clk_bidir_p, clk_dir, clk_m2c_n, clk_m2c_p,
        dp_c2m_n, dp_c2m_p, dp_m2c_n, dp_m2c_p, ga0, ga1,
        gbtclk_m2c_n, gbtclk_m2c_p, ha_n, ha_p, hb_n, hb_p, la_n,
        la_p, pg_c2m, pg_m2c, prsnt_m2c_l, scl, sda, tck, tdi, tdo,
        tms, trst_l, vio_b_m2c, vref_a_m2c, vref_b_m2c);
    inout [0:1] clk_bidir_n;
    inout [0:1] clk_bidir_p;
    input clk_dir;
    input [0:1] clk_m2c_n;
    input [0:1] clk_m2c_p;
    output [0:9] dp_c2m_n;
    output [0:9] dp_c2m_p;
    input [0:9] dp_m2c_n;
    input [0:9] dp_m2c_p;
    output ga0;
    output ga1;
    input [0:1] gbtclk_m2c_n;
    input [0:1] gbtclk_m2c_p;
    inout [0:23] ha_n;
    inout [0:23] ha_p;
    inout [0:21] hb_n;
    inout [0:21] hb_p;
    inout [0:33] la_n;
    inout [0:33] la_p;
    output pg_c2m;
    input pg_m2c;
    input prsnt_m2c_l;
    output scl;
    inout sda;
    output tck;
    output tdi;
    input tdo;
    output tms;
    output trst_l;
    input vio_b_m2c;
    input vref_a_m2c;
    input vref_b_m2c;


    initial
        begin
        end

endmodule
