-- generated by newgenasym Wed May 20 13:40:49 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fmc_hpc_generic is
    port (    
	CLK_BIDIR_N: INOUT  STD_LOGIC_VECTOR (0 TO 1);    
	CLK_BIDIR_P: INOUT  STD_LOGIC_VECTOR (0 TO 1);    
	CLK_DIR:   IN     STD_LOGIC;    
	CLK_M2C_N: IN     STD_LOGIC_VECTOR (0 TO 1);    
	CLK_M2C_P: IN     STD_LOGIC_VECTOR (0 TO 1);    
	DP_C2M_N:  OUT    STD_LOGIC_VECTOR (0 TO 9);    
	DP_C2M_P:  OUT    STD_LOGIC_VECTOR (0 TO 9);    
	DP_M2C_N:  IN     STD_LOGIC_VECTOR (0 TO 9);    
	DP_M2C_P:  IN     STD_LOGIC_VECTOR (0 TO 9);    
	GA0:       OUT    STD_LOGIC;    
	GA1:       OUT    STD_LOGIC;    
	GBTCLK_M2C_N: IN     STD_LOGIC_VECTOR (0 TO 1);    
	GBTCLK_M2C_P: IN     STD_LOGIC_VECTOR (0 TO 1);    
	HA_N:      INOUT  STD_LOGIC_VECTOR (0 TO 23);    
	HA_P:      INOUT  STD_LOGIC_VECTOR (0 TO 23);    
	HB_N:      INOUT  STD_LOGIC_VECTOR (0 TO 21);    
	HB_P:      INOUT  STD_LOGIC_VECTOR (0 TO 21);    
	LA_N:      INOUT  STD_LOGIC_VECTOR (0 TO 33);    
	LA_P:      INOUT  STD_LOGIC_VECTOR (0 TO 33);    
	PG_C2M:    OUT    STD_LOGIC;    
	PG_M2C:    IN     STD_LOGIC;    
	PRSNT_M2C_L: IN     STD_LOGIC;    
	SCL:       OUT    STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TCK:       OUT    STD_LOGIC;    
	TDI:       OUT    STD_LOGIC;    
	TDO:       IN     STD_LOGIC;    
	TMS:       OUT    STD_LOGIC;    
	TRST_L:    OUT    STD_LOGIC;    
	VIO_B_M2C: IN     STD_LOGIC;    
	VREF_A_M2C: IN     STD_LOGIC;    
	VREF_B_M2C: IN     STD_LOGIC);
end fmc_hpc_generic;
