// generated by newgenasym  Mon May 13 07:59:23 2024


module sn74axc8t245rhlr (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8, dir1,
        dir2, expad, gnd1, gnd2, \oe* , vcca, vccb1, vccb2);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout dir1;
    inout dir2;
    inout [4:0] expad;
    inout gnd1;
    inout gnd2;
    inout \oe* ;
    inout vcca;
    inout vccb1;
    inout vccb2;


    initial
        begin
        end

endmodule
