-- generated by newgenasym Mon May 13 07:59:23 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74axc8t245rhlr is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	B6:        INOUT  STD_LOGIC;    
	B7:        INOUT  STD_LOGIC;    
	B8:        INOUT  STD_LOGIC;    
	DIR1:      INOUT  STD_LOGIC;    
	DIR2:      INOUT  STD_LOGIC;    
	EXPAD:     INOUT  STD_LOGIC_VECTOR (4 DOWNTO 0);    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\oe*\:     INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB1:     INOUT  STD_LOGIC;    
	VCCB2:     INOUT  STD_LOGIC);
end sn74axc8t245rhlr;
