// generated by newgenasym  Mon May 11 17:24:54 2015


module \854s058i  (npclk, nq, pclk, q, sel1, sel2, selo);
    input [7:0] npclk;
    output nq;
    input [7:0] pclk;
    output q;
    input sel1;
    input sel2;
    input selo;


    initial
        begin
        end

endmodule
