-- generated by newgenasym Mon May 11 17:24:54 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \854s058i\ is
    port (    
	NPCLK:     IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	NQ:        OUT    STD_LOGIC;    
	PCLK:      IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	Q:         OUT    STD_LOGIC;    
	SEL1:      IN     STD_LOGIC;    
	SEL2:      IN     STD_LOGIC;    
	SELO:      IN     STD_LOGIC);
end \854s058i\;
