-- generated by newgenasym Thu May 27 12:51:36 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SFP_CAGE_X4 is
    port (    
	NC:        OUT    STD_LOGIC);
end SFP_CAGE_X4;
