// generated by newgenasym  Wed Sep 02 14:51:22 2009


module con160p_40cdgh (c, d, g, h);
    inout [40:1] c;
    inout [40:1] d;
    inout [40:1] g;
    inout [40:1] h;


    initial
        begin
        end

endmodule
