-- generated by newgenasym Wed Sep 02 14:51:22 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON160P_40CDGH is
    port (    
	C:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	D:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	G:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	H:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1));
end CON160P_40CDGH;
