// generated by newgenasym  Mon Oct 21 14:58:48 2013


module \24aa025e48  (a0, a1, a2, scl, sda, vcc, vss);
    input a0;
    input a1;
    input a2;
    input scl;
    inout sda;
    input vcc;
    input vss;


    initial
        begin
        end

endmodule
